#!/usr/bin/perl -w
#####################################################################
# Framework to run SQL Queries on Avenir Databases
#
# This program is wrote to run SQL queries using a Perl Framework
# to do data analysis
# tab==4 spaces
#
# Author: Nevin Jojo
######################################################################

use strict;
use warnings;

use 5.010;
use Getopt::Long qw(GetOptions);
use File::Find;

use Avenir::Common::OBJ::DB;
use Avenir::Common::Syslog qw(:all);

use File::Basename;
use lib dirname (__FILE__) . "/modules";
use sqlManager;
use fileWriter;

######################################################################
# Variables
######################################################################

our $src    = 'scripts/';           # source path for scripts
our $dest;                          # destination path for reports
our $format = 'txt';                # format of the report file
our $client = 'aix';                # client name

######################################################################
# Processes
######################################################################

##
# returns an array of sql file(s) that will be executed
##
sub find_files
{
    my @dirs = shift();
    my @files;

    find({ wanted => sub { push @files, $File::Find::name } , no_chdir => 1 }, @dirs);
    return @files;
}


##
# checks if the flags values
##
GetOptions(
    'src|s=s' => \$src,
    'dest|d=s' => \$dest,
    'format|f=s' => \$format,
    'client|c=s' => \$client,
) or die "Usage: -src /PATH/TO/FILE\n
          Usage: -dest /PATH/TO/FILE\n
          Usage: -format txt or -f csv\n
          Usage: -client aix or -c aix\n";


######################################################################
# Main
######################################################################

# open DB
my $db = Avenir::Common::OBJ::DB->new();


# array of sql file(s)
my @files = find_files($src);


# process - Read & execute Queries; report results
read_sql($db, \@files);


# close DB
$db->disconnect;

