#!/usr/bin/perl -w
#####################################################################
# Framework to run SQL Queries on Avenir Databases
#
# This program is wrote to run SQL queries using a Perl Framework
# to do data analysis
# tab==4 spaces
#
# Author: Nevin Jojo
######################################################################

use strict;
use warnings;

use 5.010;

use Avenir::Common::OBJ::DB;
use Avenir::Common::Syslog qw(:all);


######################################################################
# Processes
######################################################################

##
# read SQL files
##
sub read_sql
{
    my $db = shift;
    my $dbh = $db->dbh;

    my $sql_file = $ARGV[0];
    
    if (not defined $sql_file) {
        print STDERR "SQL file not defined in command line..\n";
    }
    
    my $content;

    open(SQL, '<', $sql_file) or open(SQL, "<scripts/$sql_file") or die "Can't open $sql_file: $!\n";
        local $/;
        $content = <SQL>;
    close(SQL);

    my $sth = $dbh->prepare($content) or die("Can't prepare the sql statement");

    $sth->execute() or die("Can't execute sql statements");

    &report_results($sth);
}


##
# report results from SQL query
##
sub report_results
{
    my $sth = shift;
    my $filename = $ARGV[1];

    if (not defined $filename) {
        warn "Report file not specified; Saving results in 'reports/report.txt'.\n";
        $filename = "report.txt";
    }

    open(my $fh, ">reports/$filename") or die("Could not open file '/reports/$filename'!");
    binmode($fh, ":utf8");

    while(my @ref = $sth->fetchrow_array())
    {
        print $fh join(',',@ref),"\n";
    }
    close($fh);
}

######################################################################
# Main
######################################################################

# open DB

my $db = Avenir::Common::OBJ::DB->new();


# process - Read SQL Queries from .sql file

&read_sql($db);


# close DB

$db->disconnect;

