#!/usr/bin/perl -w
######################################################################
# Test Program in Avenir Style
#
# tab==4 spaces please
######################################################################

use strict;
use warnings;

use 5.10.1;

use Avenir::Common::OBJ::DB;
use Avenir::Common::Syslog qw(:all);


######################################################################
# constants
######################################################################

use constant
{
    TEST_CONST                  => 60,
};


######################################################################
# processes
######################################################################

##
# process all
#
sub process_all
{
    my $db      = shift;

    my $dbh     = $db->dbh;
    my $sth     = $dbh->prepare("
        SELECT
            id,category,level,action,detail,username,objid,objtype,objversion,objdata,created
        FROM
            audit
        ORDER BY
            id ASC
        LIMIT
            100
    ");
    $sth->execute();

    while (my $ref = $sth->fetchrow_hashref())
    {
        syslog LOG_DEBUG, "id=%d\tuser=%s\taction=%s", $ref->{'id'}, $ref->{'username'}, $ref->{'action'};
    }
}


######################################################################
# main
######################################################################

# open syslog

openlog "test", LOG_PID;
setlogmask LOG_DEBUG;


# open DB

my $db = Avenir::Common::OBJ::DB->new();


# process

&process_all($db);


# close DB

$db->disconnect;


# close syslog

closelog;

